"""Add department request fields

Revision ID: 20260821_department_requests
Revises: 4e2ed61991ff
Create Date: 2026-08-21

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260821_department_requests'
down_revision = '4e2ed61991ff'
branch_labels = None
depends_on = '4e2ed61991ff'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create department_request_status enum
    department_request_status_enum = postgresql.ENUM('none', 'pending', 'approved', 'rejected', name='departmentrequeststatus', create_type=False)
    department_request_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Add auto_accept_requests to departments table
    op.add_column('departments', sa.Column('auto_accept_requests', sa.Boolean(), nullable=False, server_default='false'))
    
    # Add department request fields to users table
    op.add_column('users', sa.Column('requested_department_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('department_request_status', department_request_status_enum, nullable=False, server_default='none'))
    op.add_column('users', sa.Column('requested_at', sa.DateTime(), nullable=True))
    
    # Add foreign key for requested_department_id using the correct syntax
    op.create_foreign_key(
        constraint_name='fk_users_requested_department_id',
        source_table='users',
        referent_table='departments',
        local_cols=['requested_department_id'],
        remote_cols=['id'],
        ondelete='SET NULL'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key
    op.drop_constraint('fk_users_requested_department_id', 'users', type_='foreignkey')
    
    # Drop columns from users table
    op.drop_column('users', 'requested_at')
    op.drop_column('users', 'department_request_status')
    op.drop_column('users', 'requested_department_id')
    
    # Drop column from departments table
    op.drop_column('departments', 'auto_accept_requests')
    
    # Drop enum
    postgresql.ENUM(name='departmentrequeststatus', create_type=False).drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###