"""Initial schema: users, roles, schools, departments, permissions, audit_log

Revision ID: 4e2ed61991ff
Revises: 
Create Date: 2026-08-06 15:09:54.582626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e2ed61991ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enums with checkfirst - use lowercase to match Python enum values
    user_role_enum = postgresql.ENUM('superadmin', 'admin', 'checker', 'auditor', 'viewer', name='userrole', create_type=False)
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    user_status_enum = postgresql.ENUM('active', 'archived', name='userstatus', create_type=False)
    user_status_enum.create(op.get_bind(), checkfirst=True)
    
    school_status_enum = postgresql.ENUM('active', 'deactivated', name='schoolstatus', create_type=False)
    school_status_enum.create(op.get_bind(), checkfirst=True)
    
    department_status_enum = postgresql.ENUM('active', 'archived', name='departmentstatus', create_type=False)
    department_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Create schools table
    op.create_table('schools',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('code', sa.String(50), unique=True, nullable=False),
        sa.Column('status', school_status_enum, nullable=False),
        sa.Column('address', sa.Text()),
        sa.Column('contact_email', sa.String(255)),
        sa.Column('contact_phone', sa.String(50)),
        sa.Column('configuration', postgresql.JSONB(), server_default='{}'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deactivated_at', sa.DateTime())
    )
    op.create_index(op.f('ix_schools_status'), 'schools', ['status'])
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'])
    
    # Create departments table
    op.create_table('departments',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('school_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('code', sa.String(50), nullable=False),
        sa.Column('status', department_status_enum, nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('head_user_id', postgresql.UUID(as_uuid=True)),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('archived_at', sa.DateTime()),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_departments_school_id'), 'departments', ['school_id'])
    op.create_index(op.f('ix_departments_status'), 'departments', ['status'])
    op.create_index(op.f('ix_departments_school_code'), 'departments', ['school_id', 'code'], unique=True)
    
    # Create users table
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('neon_auth_user_id', sa.String(255), unique=True, nullable=False),
        sa.Column('email', sa.String(255), unique=True, nullable=False),
        sa.Column('full_name', sa.String(255), nullable=False),
        sa.Column('school_id', postgresql.UUID(as_uuid=True)),
        sa.Column('department_id', postgresql.UUID(as_uuid=True)),
        sa.Column('status', user_status_enum, nullable=False),
        sa.Column('roles', postgresql.JSONB(), server_default='[]'),
        sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('mfa_secret', sa.String(255)),
        sa.Column('phone', sa.String(50)),
        sa.Column('employee_id', sa.String(50), unique=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('archived_at', sa.DateTime()),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL')
    )
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'])
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'])
    op.create_index(op.f('ix_users_status'), 'users', ['status'])
    op.create_index(op.f('ix_users_neon_auth_user_id'), 'users', ['neon_auth_user_id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'])
    
    # Create user_school_grants table
    op.create_table('user_school_grants',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('school_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('granted_by_user_id', postgresql.UUID(as_uuid=True)),
        sa.Column('granted_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime()),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL')
    )
    op.create_index(op.f('ix_user_school_grants_user_school'), 'user_school_grants', ['user_id', 'school_id'], unique=True)
    op.create_index(op.f('ix_user_school_grants_is_active'), 'user_school_grants', ['is_active'])
    
    # Create permissions table
    op.create_table('permissions',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('module', sa.String(100), nullable=False),
        sa.Column('action', sa.String(100), nullable=False),
        sa.Column('role', user_role_enum, nullable=False),
        sa.Column('scope_constraint', sa.String(50)),
        sa.Column('is_allowed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False)
    )
    op.create_index(op.f('ix_permissions_module_action_role'), 'permissions', ['module', 'action', 'role'], unique=True)
    op.create_index(op.f('ix_permissions_role'), 'permissions', ['role'])
    
    # Create audit_log_entries table
    op.create_table('audit_log_entries',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True)),
        sa.Column('school_id', postgresql.UUID(as_uuid=True)),
        sa.Column('department_id', postgresql.UUID(as_uuid=True)),
        sa.Column('action', sa.String(100), nullable=False),
        sa.Column('entity_type', sa.String(100), nullable=False),
        sa.Column('entity_id', postgresql.UUID(as_uuid=True)),
        sa.Column('old_values', postgresql.JSONB()),
        sa.Column('new_values', postgresql.JSONB()),
        sa.Column('ip_address', sa.String(50)),
        sa.Column('user_agent', sa.Text()),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL')
    )
    op.create_index(op.f('ix_audit_log_entries_timestamp'), 'audit_log_entries', ['timestamp'])
    op.create_index(op.f('ix_audit_log_entries_user_id'), 'audit_log_entries', ['user_id'])
    op.create_index(op.f('ix_audit_log_entries_school_id'), 'audit_log_entries', ['school_id'])
    op.create_index(op.f('ix_audit_log_entries_entity'), 'audit_log_entries', ['entity_type', 'entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order
    op.drop_index(op.f('ix_audit_log_entries_entity'), 'audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_school_id'), 'audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_user_id'), 'audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_timestamp'), 'audit_log_entries')
    op.drop_table('audit_log_entries')
    
    op.drop_index(op.f('ix_permissions_role'), 'permissions')
    op.drop_index(op.f('ix_permissions_module_action_role'), 'permissions')
    op.drop_table('permissions')
    
    op.drop_index(op.f('ix_user_school_grants_is_active'), 'user_school_grants')
    op.drop_index(op.f('ix_user_school_grants_user_school'), 'user_school_grants')
    op.drop_table('user_school_grants')
    
    op.drop_index(op.f('ix_users_email'), 'users')
    op.drop_index(op.f('ix_users_neon_auth_user_id'), 'users')
    op.drop_index(op.f('ix_users_status'), 'users')
    op.drop_index(op.f('ix_users_department_id'), 'users')
    op.drop_index(op.f('ix_users_school_id'), 'users')
    op.drop_table('users')
    
    op.drop_index(op.f('ix_departments_school_code'), 'departments')
    op.drop_index(op.f('ix_departments_status'), 'departments')
    op.drop_index(op.f('ix_departments_school_id'), 'departments')
    op.drop_table('departments')
    
    op.drop_index(op.f('ix_schools_code'), 'schools')
    op.drop_index(op.f('ix_schools_status'), 'schools')
    op.drop_table('schools')
    
    # Drop enums
    postgresql.ENUM(name='departmentstatus', create_type=False).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='schoolstatus', create_type=False).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='userstatus', create_type=False).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='userrole', create_type=False).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
